# Generated by Django 4.2.1 on 2023-05-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDataTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('food', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('linkImg', models.URLField(max_length=500)),
                ('restaurantImg', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'FoodTest',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('authentication_id', models.IntegerField()),
                ('vendor_category_en', models.CharField(max_length=255)),
                ('vendor_category_id', models.IntegerField()),
                ('delivery_charge', models.FloatField()),
                ('serving_distance', models.IntegerField()),
                ('OpeningTime', models.CharField(max_length=255)),
                ('prepration_time', models.IntegerField()),
                ('discount_percentage', models.FloatField()),
                ('vendor_rating', models.FloatField()),
                ('vendor_tag', models.CharField(max_length=255)),
                ('vendor_tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('vendor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dataTest',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userTests',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user')),
                ('vendor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
            ],
            options={
                'db_table': 'ReviewTest',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('complaint', models.BooleanField(default=True)),
                ('review', models.TextField()),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user')),
                ('vendor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
            ],
            options={
                'db_table': 'ComplaintTest',
            },
        ),
    ]
