# Generated by Django 4.2.1 on 2023-05-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='my_users',
        ),
    ]
