# Generated by Django 4.2.1 on 2023-05-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
