# Generated by Django 4.2.1 on 2023-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDataTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('food', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('linkImg', models.URLField(max_length=500)),
                ('restaurantImg', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'FoodTest',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('authentication_id', models.IntegerField()),
                ('vendor_category_en', models.CharField(max_length=255)),
                ('vendor_category_id', models.IntegerField()),
                ('delivery_charge', models.FloatField()),
                ('serving_distance', models.IntegerField()),
                ('OpeningTime', models.CharField(max_length=255)),
                ('prepration_time', models.IntegerField()),
                ('discount_percentage', models.FloatField()),
                ('vendor_rating', models.FloatField()),
                ('vendor_tag', models.CharField(max_length=255)),
                ('vendor_tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('vendor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dataTest',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'ReviewTest',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='userTest',
        ),
    ]
