# Generated by Django 4.2.1 on 2023-05-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_fooddatatest_restaurant_review_user_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='userTests',
        ),
    ]
